# Triangular, pentagonal, and hexagonal
# 
# Problem 45
# 
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# 
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.


require_relative 'euler_methods.rb'


def euler45(n)
  starting_value = 286
  pentagons = pentagon_array(n)
  hexagons = hexagon_array(n)
  starting_value.upto(n) do |i|
    triangle = i * (i + 1) / 2
    puts triangle
    if pentagons.include?(triangle) and hexagons.include?(triangle) then return triangle end
  end
end


# n is a (calculated) estimate of the amount of data needed to run through to find the solution.
n =  100000

answer = euler45(n) 

puts "The answer to Project Euler problem 45 is #{answer}."

# Takes 5 minutes or so.