# Pentagon numbers
# 
# Problem 44
# 
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal 
# numbers are:
# 
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# 
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 
# 70 − 22 = 48, is not pentagonal.
# 
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are 
# pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

require_relative 'euler_methods.rb'


def euler44(n)
  d = 10000000000
  array = pentagon_array(n)
  array_check = pentagon_array(n * 2)
  
  array.each do |i|
    catch (:done) do
    array.each do |j|
      throw :done if j > i
      if array_check.include?(i + j) and array_check.include?(i - j) and i - j < d
        puts "d is #{d}"
        d = i - j
      end
    end
    end
  end
  
  d      
end

# n is a (calculated) estimate of the amount of data needed to run through to find the solution.
n = 10000

answer = euler44(n) 

puts "The answer to Project Euler problem 44 is #{answer}."